### ISSUE TITLE
Can we implement Google Ads Enhanced Conversions?

### ISSUE THREAD

**Issue by arronmoss** [zero1limited/magento2-hyva-improved-checkout-success-page#1]
we need an option in MAP for 'Google Ads Enhanced conversions' ref https://support.google.com/google-ads/answer/9888656
Arron has done this, you can get the scope directly from him. 
QUESTION I ASK MYSELF, is this better being its own extension? up for discussion.

Also, order date and currency not formatted nicely.

**Comment by arronmoss** [comment]
@sean-zero1 trying to see if putting stuff like this direct into the repo helps.

**Comment by sean-zero1** [comment]
Hi @arronmoss 
Enhanced Conversions will be done within another module which I'll send to you once completed. Thanks!
